name: "LLNL Software Portal"
author: "LLNL Open Source <open-source@llnl.gov>"
title: LLNL Software Portal
description: "Lawrence Livermore National Laboratory Software Portal"
remote_theme: LLNL/Jekyll-LLNL-Theme@main

url: "https://softwareunderground.github.io"
repo_url: "https://github.com/softwareunderground/llnl.github.io"
baseurl: "llnl.github.io"

# LLNL Piwik Analytics https://analytics.llnl.gov
# piwik_id: 250

# Google Analytics ID
#google_analytics:
#  tracking_id: UA-75179431-1

# Twitter username (used by jekyll-seo-tag)
twitter:
  username: swung_org

# GitHub Metadata -- https://github.com/jekyll/github-metadata
repository: softwareunderground/llnl.github.io
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

kramdown:
  auto_ids: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/news/:year/:month/:day/:title/"

permalink: pretty

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - README.md
    - Makefile
    - build
